// Alaska locations with aurora viewing thresholds
// Kp thresholds based on magnetic latitude — lower latitude needs higher Kp

export const LOCATIONS = {
  fairbanks: {
    name: 'Fairbanks',
    slug: 'fairbanks',
    lat: 64.84,
    lon: -147.72,
    kpVisible: 1,
    kpGood: 3,
    nwsOffice: 'AFG',
    gridX: null, // looked up at runtime
    gridY: null,
    tips: 'Head to Cleary Summit or Murphy Dome for dark skies away from city lights.',
  },
  anchorage: {
    name: 'Anchorage',
    slug: 'anchorage',
    lat: 61.22,
    lon: -149.90,
    kpVisible: 3,
    kpGood: 5,
    nwsOffice: 'AFC',
    gridX: null,
    gridY: null,
    tips: 'Drive north on the Glenn Highway past Eagle River for darker skies. Knik River access road is popular.',
  },
  'palmer-wasilla': {
    name: 'Palmer-Wasilla',
    slug: 'palmer-wasilla',
    lat: 61.60,
    lon: -149.11,
    kpVisible: 3,
    kpGood: 5,
    nwsOffice: 'AFC',
    gridX: null,
    gridY: null,
    tips: 'Hatcher Pass offers excellent dark sky viewing above the valley fog. Dress warm — it\'s exposed.',
  },
  denali: {
    name: 'Denali',
    slug: 'denali',
    lat: 63.73,
    lon: -148.91,
    kpVisible: 2,
    kpGood: 3,
    nwsOffice: 'AFG',
    gridX: null,
    gridY: null,
    tips: 'Denali\'s remote location means very dark skies. The park road pullouts offer unobstructed northern views.',
  },
  'kenai-soldotna': {
    name: 'Kenai/Soldotna',
    slug: 'kenai-soldotna',
    lat: 60.55,
    lon: -151.26,
    kpVisible: 4,
    kpGood: 5,
    nwsOffice: 'AFC',
    gridX: null,
    gridY: null,
    tips: 'The Kenai Peninsula needs stronger storms but offers beach viewing along the Cook Inlet.',
  },
  juneau: {
    name: 'Juneau',
    slug: 'juneau',
    lat: 58.30,
    lon: -134.42,
    kpVisible: 5,
    kpGood: 6,
    nwsOffice: 'AJK',
    gridX: null,
    gridY: null,
    tips: 'Juneau\'s southern latitude and frequent cloud cover make aurora rare. Mendenhall Glacier area offers dark viewing when skies cooperate.',
  },
};

export const LOCATION_SLUGS = Object.keys(LOCATIONS);
